server {
    listen 80;
    server_name _;

    location / {
        client_max_body_size 500m;
        set $forwarded_port 80;
        if ($http_x_forwarded_proto = "https") {
            set $forwarded_port 443;
        }
        if ($http_x_forwarded_port) {
            set $forwarded_port $http_x_forwarded_port;
        }
        if ($http_host ~* ":([0-9]+)$") {
            set $forwarded_port $1;
        }

        set $the_scheme $scheme;
        if ($http_x_forwarded_proto = "https") {
            set $the_scheme "https";
        }

        proxy_pass http://app-blue:80;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $the_scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Port $forwarded_port;
    }
}
