x-app-prod: &app-prod-template
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    # Resource limits untuk production
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M

services:
  app-blue:
    <<: *app-prod-template
  app-green:
    <<: *app-prod-template