x-app: &app-template
    env_file:
        - .env
    build:
        context: .
        dockerfile: Dockerfile
    image: dpd-award-app:latest
    extra_hosts:
        - 'host.docker.internal:host-gateway'
    volumes:
        - './storage:/var/www/html/storage'
    networks:
        - dpd-award
    restart: unless-stopped
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost/"]
        interval: 5s
        timeout: 5s
        retries: 15

services:
    proxy:
        image: nginx:alpine
        ports:
            - '8005:80'
        volumes:
            - ./docker/proxy:/etc/nginx/conf.d
        networks:
            - dpd-award
        restart: always

    app-blue:
        <<: *app-template

    app-green:
        <<: *app-template

networks:
    dpd-award:
        driver: bridge